del /Q /S "C:\temp\App_Data\*.ix"
del /Q /S "C:\temp\App_Data\*.ixp"
del /Q /S "C:\temp\App_Data\*.pos"
del /Q /S "C:\temp\App_Data\*.vec"
del /Q /S "C:\temp\App_Data\*.zip"
del /Q /S "C:\projects\resin\src\Sir.DbUtil\bin\Debug\netcoreapp2.1\log\*.log"
del /Q /S "C:\projects\resin\src\Sir.HttpServer\log\*.log"