call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 1000 --take 1000
call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 2000 --take 1000
call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 3000 --take 1000
call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 4000 --take 1000
call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 5000 --take 1000
call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 6000 --take 1000
call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 7000 --take 1000
call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 8000 --take 1000
call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 9000 --take 1000
call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 10000 --take 1000
call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 11000 --take 1000
call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 12000 --take 1000
call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 13000 --take 1000
call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 14000 --take 1000
call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 15000 --take 1000
call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 16000 --take 1000
call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 17000 --take 1000
call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 18000 --take 1000
call rn write-pg --source-dir C:\temp\pgdvd --dir c:\temp\resin_data\pg --pk url --skip 19000 --take 1000

