call rn write --file c:\temp\0wikipedia.json --dir d:\resin\wikipedia --skip 0 --take 1000000
call rn write --file c:\temp\1wikipedia.json --dir d:\resin\wikipedia --skip 0 --take 1000000
call rn write --file c:\temp\2wikipedia.json --dir d:\resin\wikipedia --skip 0 --take 1000000
call rn write --file c:\temp\3wikipedia.json --dir d:\resin\wikipedia --skip 0 --take 1000000
call rn write --file c:\temp\4wikipedia.json --dir d:\resin\wikipedia --skip 0 --take 1000000
call rn write --file c:\temp\5wikipedia.json --dir d:\resin\wikipedia --skip 0 --take 1000000
call rn write --file c:\temp\6wikipedia.json --dir d:\resin\wikipedia --skip 0 --take 1000000
call rn write --file c:\temp\7wikipedia.json --dir d:\resin\wikipedia --skip 0 --take 1000000
call rn write --file c:\temp\8wikipedia.json --dir d:\resin\wikipedia --skip 0 --take 1000000
call rn write --file c:\temp\9wikipedia.json --dir d:\resin\wikipedia --skip 0 --take 1000000
call rn write --file c:\temp\10wikipedia.json --dir d:\resin\wikipedia --skip 0 --take 1000000